package Selenium.ide;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import io.github.bonigarcia.wdm.WebDriverManager;
public class Ejercicio9SeleniumTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty("webdriver.chrome.driver","ide\\chromedriver.exe");
	WebDriverManager.chromedriver().setup();
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1SignInconusuarioincorrecto() {
    driver.get("https://www.saucedemo.com/");
    driver.manage().window().setSize(new Dimension(1552, 849));
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("odieste");
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("odieste");
    driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"error\"]")).click();
    assertThat(driver.findElement(By.cssSelector("*[data-test=\"error\"]")).getText(), is("Epic sadface: Username and password do not match any user in this service"));
  }
  @Test
  public void test2SignIncorrecto() {
    driver.get("https://www.saucedemo.com/");
    driver.manage().window().setSize(new Dimension(1552, 849));
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
    driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
    driver.findElement(By.cssSelector(".header_secondary_container")).click();
    assertThat(driver.findElement(By.cssSelector(".title")).getText(), is("PRODUCTS"));
  }
  
  @Test
  public void test3About() {
    driver.get("https://www.saucedemo.com/");
    driver.manage().window().setSize(new Dimension(1552, 849));
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
    driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
    driver.findElement(By.id("react-burger-menu-btn")).click();
    driver.findElement(By.id("about_sidebar_link")).click();
    driver.findElement(By.cssSelector(".hero-body")).click();
    assertThat(driver.findElement(By.cssSelector(".is-full-mobile .supertitle")).getText(), is("DEVELOP WITH CONFIDENCE"));
  }
  
  @Test
  public void test4SauceLabsBackpack() {
    driver.get("https://www.saucedemo.com/");
    driver.manage().window().setSize(new Dimension(1552, 849));
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
    driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
    driver.findElement(By.cssSelector("#item_4_title_link > .inventory_item_name")).click();
    driver.findElement(By.cssSelector("*[data-test=\"add-to-cart-sauce-labs-backpack\"]")).click();
    driver.findElement(By.linkText("1")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".inventory_item_name"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void test5SauceLabsBoltTShirt() {
    driver.get("https://www.saucedemo.com/");
    driver.manage().window().setSize(new Dimension(1552, 849));
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
    driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
    driver.findElement(By.cssSelector("#item_4_title_link > .inventory_item_name")).click();
    driver.findElement(By.cssSelector("*[data-test=\"add-to-cart-sauce-labs-backpack\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
    driver.findElement(By.cssSelector("#item_1_title_link > .inventory_item_name")).click();
    driver.findElement(By.cssSelector("*[data-test=\"add-to-cart-sauce-labs-bolt-t-shirt\"]")).click();
    driver.findElement(By.linkText("2")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#item_4_title_link > .inventory_item_name"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#item_1_title_link > .inventory_item_name"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void test6EliminarSauceLabsBackpack() {
    driver.get("https://www.saucedemo.com/");
    driver.manage().window().setSize(new Dimension(1552, 849));
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
    driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
    driver.findElement(By.cssSelector("#item_4_title_link > .inventory_item_name")).click();
    driver.findElement(By.cssSelector("*[data-test=\"add-to-cart-sauce-labs-backpack\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
    driver.findElement(By.cssSelector("#item_1_title_link > .inventory_item_name")).click();
    driver.findElement(By.cssSelector("*[data-test=\"add-to-cart-sauce-labs-bolt-t-shirt\"]")).click();
    driver.findElement(By.linkText("2")).click();
    driver.findElement(By.cssSelector("*[data-test=\"remove-sauce-labs-backpack\"]")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#item_4_title_link > .inventory_item_name"));
      assert(elements.size() == 0);
    }
  }
  @Test
  public void test7Checkout() {
    driver.get("https://www.saucedemo.com/");
    driver.manage().window().setSize(new Dimension(1552, 849));
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
    driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
    driver.findElement(By.cssSelector("#item_4_title_link > .inventory_item_name")).click();
    driver.findElement(By.cssSelector("*[data-test=\"add-to-cart-sauce-labs-backpack\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
    driver.findElement(By.cssSelector("#item_1_title_link > .inventory_item_name")).click();
    driver.findElement(By.cssSelector("*[data-test=\"add-to-cart-sauce-labs-bolt-t-shirt\"]")).click();
    driver.findElement(By.linkText("2")).click();
    driver.findElement(By.cssSelector("*[data-test=\"checkout\"]")).click();
    assertThat(driver.findElement(By.cssSelector(".title")).getText(), is("CHECKOUT: YOUR INFORMATION"));
  }
  
  
  @Test
  public void test8Continue() {
    driver.get("https://www.saucedemo.com/");
    driver.manage().window().setSize(new Dimension(1552, 849));
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
    driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
    driver.findElement(By.cssSelector("#item_4_title_link > .inventory_item_name")).click();
    driver.findElement(By.cssSelector("*[data-test=\"add-to-cart-sauce-labs-backpack\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
    driver.findElement(By.cssSelector("#item_1_title_link > .inventory_item_name")).click();
    driver.findElement(By.cssSelector("*[data-test=\"add-to-cart-sauce-labs-bolt-t-shirt\"]")).click();
    driver.findElement(By.linkText("2")).click();
    driver.findElement(By.cssSelector("*[data-test=\"firstName\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"firstName\"]")).sendKeys("Adrián");
    driver.findElement(By.cssSelector(".checkout_info")).click();
    driver.findElement(By.cssSelector("*[data-test=\"lastName\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"lastName\"]")).sendKeys("Salas Rodrigues");
    driver.findElement(By.cssSelector(".checkout_info")).click();
    driver.findElement(By.cssSelector("*[data-test=\"postalCode\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"postalCode\"]")).sendKeys("1111");
    driver.findElement(By.cssSelector("*[data-test=\"continue\"]")).click();
    driver.findElement(By.cssSelector(".title")).click();
    assertThat(driver.findElement(By.cssSelector(".title")).getText(), is("CHECKOUT: OVERVIEW"));
    driver.findElement(By.cssSelector("*[data-test=\"checkout\"]")).click();
  }
  @Test
  public void test9Finish() {
    driver.get("https://www.saucedemo.com/");
    driver.manage().window().setSize(new Dimension(1552, 849));
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
    driver.findElement(By.cssSelector("#item_4_title_link > .inventory_item_name")).click();
    driver.findElement(By.cssSelector("*[data-test=\"add-to-cart-sauce-labs-backpack\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
    driver.findElement(By.cssSelector("#item_1_title_link > .inventory_item_name")).click();
    driver.findElement(By.cssSelector("*[data-test=\"add-to-cart-sauce-labs-bolt-t-shirt\"]")).click();
    driver.findElement(By.linkText("2")).click();
    driver.findElement(By.cssSelector("*[data-test=\"checkout\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"firstName\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"firstName\"]")).sendKeys("Adrián");
    driver.findElement(By.cssSelector(".checkout_info")).click();
    driver.findElement(By.cssSelector("*[data-test=\"lastName\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"lastName\"]")).sendKeys("Salas");
    driver.findElement(By.cssSelector(".checkout_info")).click();
    driver.findElement(By.cssSelector("*[data-test=\"postalCode\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"postalCode\"]")).sendKeys("1111");
    driver.findElement(By.cssSelector("*[data-test=\"continue\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"finish\"]")).click();
    driver.findElement(By.id("checkout_complete_container")).click();
    assertThat(driver.findElement(By.cssSelector(".complete-header")).getText(), is("THANK YOU FOR YOUR ORDER"));
    driver.findElement(By.linkText("2")).click();
    
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#item_4_title_link > .inventory_item_name"));
      assert(elements.size() == 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#item_1_title_link > .inventory_item_name"));
      assert(elements.size() == 0);
    }
  }
  @Test
  public void test10Pricelowtohigh() {
    driver.get("https://www.saucedemo.com/");
    driver.manage().window().setSize(new Dimension(1552, 849));
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
    driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"product_sort_container\"]")).click();
    driver.findElement(By.cssSelector(".inventory_item:nth-child(1) .inventory_item_price")).click();
    driver.findElement(By.cssSelector(".inventory_item:nth-child(1) .inventory_item_price")).click();
    driver.findElement(By.cssSelector(".inventory_item:nth-child(1) .inventory_item_price")).click();
    assertThat(driver.findElement(By.cssSelector(".inventory_item:nth-child(1) .inventory_item_price")).getText(), is("$7.99"));
    driver.findElement(By.cssSelector(".inventory_item:nth-child(6) .inventory_item_price")).click();
    assertThat(driver.findElement(By.cssSelector(".inventory_item:nth-child(6) .inventory_item_price")).getText(), is("$49.99"));
  }
}
